In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('perceptron_algorithm.csv', delimiter=',', header=None)
df[:5]

0         1  2
0  0.78051 -0.063669  1
1  0.28774  0.291390  1
2  0.40714  0.178780  1
3  0.29230  0.421700  1
4  0.50922  0.352560  1

In [6]:
X = np.array(df.iloc[:, :-1])
X[:2]

array([[ 0.78051 , -0.063669],
       [ 0.28774 ,  0.29139 ]])

In [7]:
y = np.array(df.iloc[:, -1])
y[:2]

array([1, 1], dtype=int64)

In [14]:
x_min, x_max = min(X.T[0]), max(X.T[0])
y_min, y_max = min(X.T[1]), max(X.T[1])
learn_rate = 0.01

In [9]:
print(x_min, x_max)

0.0084492 1.0


In [10]:
print(y_min, y_max)

-0.063669 1.0


In [11]:
W = np.array(np.random.rand(2,1))
b = np.random.rand(1)[0] + x_max

In [12]:
W

array([[0.26927871],
       [0.58480331]])

In [13]:
b

1.0067836018308216

In [20]:
(np.matmul(X[0],W)+b)[0]

1.179724489476927

# Algorithm

In [21]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    for i in range(0, len(X)):
        y_cap = prediction(X[i],W,b)
        if y[i] - y_cap == 1:
            W[0] += learn_rate * X[i][0]
            W[1] += learn_rate * X[i][1]
            b += learn_rate
        elif y[i] - y_cap == -1:
            W[0] -= learn_rate * X[i][0]
            W[1] -= learn_rate * X[i][1]
            b -= learn_rate
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines